<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="BenchmarkDotNet" Version="0.15.8"/>
        <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.0"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.Common" Version="5.0.0"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0"/>
        <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="10.0.10"/>
        <PackageVersion Include="Shouldly" Version="4.3.0"/>
        <PackageVersion Include="TUnit" Version="1.61.38"/>
    </ItemGroup>
</Project>